version: "3"

networks:
  traefik-public:
    external: true

services:
  pgadmin-local:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: "true"
    labels:
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.pgadmin-local-http.rule=Host(`${PGADMIN_DOMAIN}`)
      - traefik.http.routers.pgadmin-local-http.entrypoints=http
      - traefik.http.routers.pgadmin-local-http.middlewares=https-redirect
      - traefik.http.routers.pgadmin-local-https.rule=Host(`${PGADMIN_DOMAIN}`)
      - traefik.http.routers.pgadmin-local-https.entrypoints=https
      - traefik.http.routers.pgadmin-local-https.tls=true
      - traefik.http.services.pgadmin-local.loadbalancer.server.port=80
    networks:
      - traefik-public
      - recruits-internal-local

  db-local:
    image: postgres:16.2-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data-local:/var/lib/postgresql/data/
    networks:
      - recruits-internal-local
